FROM nvcr.io/nvidia/pytorch:25.09-py3

ENV TZ=Europe/Istanbul
ENV DEBIAN_FRONTEND=noninteractive

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get update && apt-get install -y tzdata

RUN apt-get update && apt-get upgrade -y \
    && apt-get install -y \
    python3 \
    python3-pip \
    git

RUN pip3 install cmake --upgrade
WORKDIR /workspace

ENV CUDNN_DIR=/usr/local/cuda
ENV LD_LIBRARY_PATH=$CUDNN_DIR/lib64:$LD_LIBRARY_PATH

ENV CUDA_HOME=/usr/local/cuda
ENV LD_LIBRARY_PATH=$CUDA_HOME/lib64:$LD_LIBRARY_PATH

RUN apt-get install libopencv-dev libgtk* libspdlog-dev libfmt-dev libboost-dev ffmpeg libavformat-dev libavcodec-dev libswscale-dev pybind11-dev libxcb-xinerama0 \
    libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xfixes0 libxcb-cursor0 libyaml-cpp-dev libwebsocketpp-dev libxkbcommon-x11-0 \
    libglib2.0-0 libdbus-1-3 -y && rm -rf /var/lib/apt/lists/* 




WORKDIR /workspace
RUN git clone --depth=1 https://github.com/opencv/opencv.git && git clone --depth=1 https://github.com/opencv/opencv_contrib.git && cd opencv && mkdir build
WORKDIR /workspace/opencv/build
RUN cmake -D CMAKE_BUILD_TYPE=RELEASE \
    #-D VIDEO_CODEC_SDK_INCLUDE_DIR:PATH="/usr/local/include" \
    #-D VIDEO_CODEC_SDK_LIBRARY_DIR:PATH="/usr/local/lib" \
    -D WITH_CUDA=ON \
    -D WITH_CUDNN=ON \
    -D OPENCV_DNN_CUDA=ON \
    -D ENABLE_FAST_MATH=1 \
    -D CUDA_FAST_MATH=1 \
    -D WITH_CUBLAS=1 \
    -D WITH_CUFFT=ON \
    -D WITH_CUBLAS=1 \
    -D WITH_NVCUVID=OFF \
    -D BUILD_opencv_cudacodec=OFF \
    #-D CUDA_ARCH_BIN=8.9 \  
    -D WITH_OPENGL=ON \
    -D WITH_FFMPEG=ON \
    -D WITH_GSTREAMER=ON \
    -D WITH_TBB=ON \
    -D BUILD_TESTS=OFF \
    -D BUILD_PERF_TESTS=OFF \
    -D BUILD_EXAMPLES=OFF \
    -D OPENCV_EXTRA_MODULES_PATH=/workspace/opencv_contrib/modules ..

RUN make -j$(nproc) && make install

#RUN pip3 install torch torchvision --upgrade --force-reinstall

RUN apt-get update && apt-get upgrade -y
RUN pip3 install onnxslim matplotlib tqdm requests psutil PyQt5
RUN pip3 install "numpy<2"


# WORKDIR /workspace
# RUN apt-get update && apt-get install -y curl gnupg2 lsb-release
# RUN curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | gpg --dearmor > /usr/share/keyrings/ros-archive-keyring.gpg
# RUN echo "deb [signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(lsb_release -sc) main" | tee /etc/apt/sources.list.d/ros2.list > /dev/null
# RUN apt-get update && apt-get install -y ros-jazzy-desktop
# RUN apt-get install -y python3-colcon-common-extensions python3-rosdep python3-vcstool
# RUN rosdep init
# RUN rosdep update

# RUN apt-get install -y \
#     libpcap-dev \
#     python3-pip \
#     libyaml-cpp-dev \
#     libzmq3-dev \
#     ros-jazzy-moveit* \
#     ros-jazzy-cont* \
#     ros-jazzy-ros2-cont* \
#     ros-jazzy-bond* \
#     ros-jazzy-diagnostic-updater* 

RUN apt-get update && apt-get upgrade -y